version: "3.7" 

networks:
    local-net:
        driver: bridge

services:
    nginx:
        container_name: nginx.dev
        build:
            context: ./nginx
        ports:
            - 10000:80
        volumes:
            - ./blog:/www/blog
        networks:
            - local-net
    php:
        container_name: php.dev
        build:
            context: ./php
        ports:
            - 9001:9000
        networks:
            - local-net
        volumes:
            - ./blog:/www/blog
    mysql:
        container_name: mysql.dev
        build:
            context: ./mysql
        image: mysql
        ports:
            - 33060:3306
        networks:
            - local-net
        command: --default-authentication-plugin=mysql_native_password --skip-name-resolve
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: admin
    adminer:
        image: adminer
        container_name: adminer.dev
        restart: always
        ports:
          - 8080:8080
        networks:
          - local-net
        links:
          - mysql
